### ISSUE TITLE
JsonNumEquals fails when MissingNode is passed

### ISSUE THREAD

**Issue by grimsa** [java-json-tools/jackson-coreutils#37]
The following code:
```java
        JsonNode original = originalJson.at("/some/path");    // produces MissingNode instance
        JsonNode updated = updatedJson.at("/some/path");
        boolean valid = JsonNumEquals.getInstance().equivalent(original, updated);
```
results in
```
java.lang.NullPointerException: unhandled token type NOT_AVAILABLE
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897)
	at com.github.fge.jackson.NodeType.getNodeType(NodeType.java:144)
	at com.github.fge.jackson.JsonNumEquals.doEquivalent(JsonNumEquals.java:68)
	at com.github.fge.jackson.JsonNumEquals.doEquivalent(JsonNumEquals.java:43)
	at com.google.common.base.Equivalence.equivalent(Equivalence.java:65)
```
The cause seems to be that there is no enum value in `com.github.fge.jackson.NodeType` that corresponds to MissingNode.

**Comment by Capstan** [comment]
From the commentary in `NodeType`, it was intended that it be a short-lived replacement until [Databind's `JsonNodeType`](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/node/JsonNodeType.html) could be used, and that has an entry for `MISSING`.

I would be happy to review contributions of either a `NodeType` entry addition of `MISSING`, or a larger refactor to use `JsonNodeType` from Databind, or both, serially.

**Comment by grimsa** [comment]
For the record, we have since switched to a more generic workaround presented here: https://github.com/java-json-tools/jackson-coreutils/issues/45#issuecomment-890330220
